# Generated by Django 4.2.4 on 2023-09-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_picturemain_photo_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='picturemain',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='sellers.realestate'),
        ),
    ]
